#!/usr/bin/env python
# -*- Mode: python -*-
#
# Copyright (C) 2000 The ViewCVS Group. All Rights Reserved.
#
# By using this file, you agree to the terms and conditions set forth in
# the LICENSE.html file which can be found at the top level of the ViewCVS
# distribution or at http://www.lyra.org/viewcvs/license-1.html.
#
# Contact information:
#   Greg Stein, PO Box 760, Palo Alto, CA, 94302
#   gstein@lyra.org, http://www.lyra.org/viewcvs/
#
# -----------------------------------------------------------------------
#
# install script for viewcvs -- temporary?
#
# ### this will eventually be replaced by autoconf plus tools. an
# ### interactive front-end to ./configure may be provided.
#
# -----------------------------------------------------------------------
#

import os, sys, string, re



## installer text
INFO_TEXT = """\

This is the ViewCVS installer.  It will allow you to choose the install
path for ViewCVS.  You will now be asked some installation questions.
Defaults are given in square brackets.  Just hit [Enter] if a default
is okay.
"""

## installer defaults
ROOT_DIR = "/usr/local/viewcvs"


## list of files for installation
## tuple (source path, destination path, install mode, true/false flag for
##        search-and-replace for LIBRARY_DIR, CONF_PATHNAME, etc...)

FILE_INFO_LIST = [
    ("cgi/viewcvs.cgi", "cgi/viewcvs.cgi", 0755, 1),
    ("cgi/queryform.cgi", "cgi/queryform.cgi", 0755, 1),
    ("cgi/query.cgi", "cgi/query.cgi", 0755, 1),
    ("cgi/granny.cgi", "cgi/granny.cgi", 0755, 1),

    ("cgi/viewcvs.conf.dist", "viewcvs.conf", 0644, 0),

    ("lib/PyFontify.py", "lib/PyFontify.py", 0644, 0),
    ("lib/commit.py", "lib/commit.py", 0644, 0),
    ("lib/compat.py", "lib/compat.py", 0644, 0),
    ("lib/config.py", "lib/config.py", 0644, 0),
    ("lib/cvsdbapi.py", "lib/cvsdbapi.py", 0644, 1),
    ("lib/database.py", "lib/database.py", 0644, 0),
    ("lib/py2html.py", "lib/py2html.py", 0644, 0),
    ("lib/rlog.py", "lib/rlog.py", 0644, 0),

    ("scripts/loginfo-handler", "scripts/loginfo-handler", 0755, 1),

    ("tools/cvsdbadmin", "tools/cvsdbadmin", 0755, 1),

    ("html-templates/queryformtemplate.html",
     "html-templates/queryformtemplate.html", 0644, 0),
    ("html-templates/querytemplate.html",
     "html-templates/querytemplate.html", 0644, 0),
    ]


def Error(text):
    print
    print "[ERROR] %s" % (text)
    sys.exit(1)
    

def MkDir(path):
    make_dirs = []

    while len(path) and not os.path.exists(path):
        make_dirs.insert(0, path)
        (path, basename) = os.path.split(path)
        
    for path in make_dirs:
        try:
            os.mkdir(path)
        except OSError, e:
            if e.errno != 13:
                Error("Unknown error creating directory %s" % (path))
            
            Error("You do not have permission to create directory %s" % (path))


## regular expressions used to find key lines the installer needs
## to rewrite
_re_library_dir = re.compile("^LIBRARY_DIR\s*=\s*.*$")
_re_conf_pathname = re.compile("^CONF_PATHNAME\s*=\s*.*$")
_re_html_template_dir = re.compile("^HTML_TEMPLATE_DIR\s*=\s*.*$")

def SetPythonPaths(line_list):
    for index in range(len(line_list)):
        line = line_list[index]

        if _re_library_dir.match(line):
            temp = os.path.join(ROOT_DIR, "lib")
            line_list[index] = "LIBRARY_DIR = \"%s\"\n" % (temp)
            continue

        if _re_conf_pathname.match(line):
            temp = os.path.join(ROOT_DIR, "viewcvs.conf")
            line_list[index] = "CONF_PATHNAME = \"%s\"\n" % (temp)
            continue

        if _re_html_template_dir.match(line):
            temp = os.path.join(ROOT_DIR, "html-templates")
            line_list[index] = "HTML_TEMPLATE_DIR = \"%s\"\n" % (temp)
            continue


def InstallFile(src_path, dest_path, mode, set_python_paths):
    try:
        line_list = open(src_path, "r").readlines()
    except IOError, e:
        Error(str(e))

    if set_python_paths:
        SetPythonPaths(line_list)

    ## write the file to the destination location
    dest_path = os.path.join(ROOT_DIR, dest_path)
    path, basename = os.path.split(dest_path)
    MkDir(path)

    try:
        open(dest_path, "w").writelines(line_list)
    except IOError, e:
        if e.errno != 13:
            Error("Unknown error writing file %s" % (dest_path))

        Error("You do not have permission to write file %s" % (dest_path))
        
    os.chmod(dest_path, mode)



## MAIN
if __name__ == "__main__":
    print INFO_TEXT
    
    ## get the install path
    temp = raw_input("Installation Path [%s]: " % (ROOT_DIR))
    temp = string.strip(temp)
    if len(temp):
        ROOT_DIR = temp
        
    ## install the files
    print
    print "Installing ViewCVS to: %s" % (ROOT_DIR)
        
    for file_info in FILE_INFO_LIST:
        (src_path, dest_path, mode, set_python_paths) = file_info
        print "        %s" % (src_path)
        InstallFile(src_path, dest_path, mode, set_python_paths)

    print
    print "Installation Complete"
