#!/usr/bin/env python
# -*- Mode: python -*-
#
# install script for viewcvs -- temporary?
#
# -----------------------------------------------------------------------
# Copyright (C) 2000 Jay Painter. All Rights Reserved.
#
# By using this file, you agree to the terms and conditions set forth below:
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# -----------------------------------------------------------------------
#
# For tracking purposes, this software is identified by:
#   $Id$
#
# -----------------------------------------------------------------------

import os, sys, string, re



## installer text
INFO_TEXT = """\

This is the ViewCVS installer.  It will allow you to choose the install
path for ViewCVS.  You will now be asked some installation questions.
Defaults are given in square brackets.  Just hit [Enter] if a default
is okay.
"""

## installer defaults
ROOT_DIR = "/usr/local/viewcvs"


## list of files for installation
FILE_LIST = [
    "cgi/viewcvs.cgi",
    "cgi/queryform.cgi",
    "cgi/query.cgi",
    "cgi/granny.cgi",

    "lib/PyFontify.py",
    "lib/cfg.py",
    "lib/commit.py",
    "lib/compat.py",
    "lib/config.py",
    "lib/cvsdbapi.py",
    "lib/database.py",
    "lib/py2html.py",
    "lib/rlog.py",

    "scripts/loginfo-handler",

    "tools/cvsdbadmin",

    "html-templates/queryformtemplate.html",
    "html-templates/querytemplate.html",
    ]

## regular expressions used to find key lines the installer needs
## to rewrite
_re_library_dir = re.compile("^LIBRARY_DIR\s*=\s*.*$")
_re_conf_pathname = re.compile("^CONF_PATHNAME\s*=\s*.*$")


def SetLoadPaths(filename):
    line_list = open(filename, "r").readlines()

    for index in range(len(line_list)):
        line = line_list[index]

        if _re_library_dir.match(line):
            temp = os.path.join(ROOT_DIR, "lib")
            line_list[index] = "LIBRARY_DIR = \"%s\"" % (temp)
            continue

        if _re_conf_pathname.match(line):
            temp = os.path.join(ROOT_DIR, "cgi", "viewcvs.conf")
            line_list[index] = "LIBRARY_DIR = \"%s\"" % (temp)
            continue

    open(filename, "w").writelines(line_list)


## MAIN
if __name__ == "__main__":
    print INFO_TEXT
    
    ## get the install path
    temp = raw_input("Installation Path [%s]: " % (ROOT_DIR))
    temp = string.strip(temp)
    if len(temp):
        ROOT_DIR = temp

    ## check to see if the path exists
    if not os.path.isdir(ROOT_DIR):
        print "Installation Path [%s] does not exist." % (ROOT_DIR)
        

