#!/bin/sh

DATE=`date +"%Y%m%d"`
EXPORTDIR="viewvc-${DATE}"
PUBLISH_DIR=/www/viewvc/nightly

# export HEAD of trunk
svn export --quiet http://viewvc.tigris.org/svn/viewvc/trunk ${EXPORTDIR} --username guest --password ""

# use Python to determine the version number, reading it from 
# viewvc.__version__
cd $EXPORTDIR/lib
VERSION=`python -c "import viewvc; print viewvc.__version__"`
TARGET=viewvc-${VERSION}-${DATE}

# make a release
cd ../tools
./make-release ${TARGET}

# remove results of last build
rm -rf ${PUBLISH_DIR}/viewvc*.tar.gz ${PUBLISH_DIR}/viewvc*.zip ${PUBLISH_DIR}/index.html

# publish new build
mv ${TARGET}.* ${PUBLISH_DIR}
cd ../..

cat > ${PUBLISH_DIR}/index.html <<EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
                      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<title>ViewVC: Nightly Snapshots</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="stylesheet" type="text/css" href="../styles.css"/>
</head>

<body>

<div id="title">
<a href="http://www.viewvc.org/"><img 
   src="../images/title.jpg" alt="ViewVC: Repository Browsing"/></a>
</div>

<div id="menu">
<p><a href="../index.html">Home</a> |
   <a href="http://viewvc.tigris.org/">Project Page</a> |
   <a href="../download.html">Download</a> |
   <a href="../contributing.html">Contributing</a> |
   <a href="./faq.html">FAQ</a> |
   <a href="http://viewvc.tigris.org/nonav/source/browse/*checkout*/viewvc/trunk/LICENSE.html">License</a> |
   <a href="../contact.html">Contact</a> |
   <a href="../who.html">About</a>
</p>
</div>

<table id="pagetable">
<tr>
<td id="pagecolumn1">

<h4>On this page:</h4>

<ul id="bookmarks">
  <li><a href="#sec-snapshots">Snapshots</a></li>
</ul>

<p><a href="http://validator.w3.org/check?uri=referer"><img
       src="http://www.w3.org/Icons/valid-xhtml10"
       alt="Valid XHTML 1.0 Strict" height="31" width="88" /></a>
</p>

</td>
<td id="pagecolumn2">

<div class="section">

<h2 id="sec-snapshots">Snapshots</h2>

<div class="section-body">
<ul>
EOF

echo "<li><a href=\"${TARGET}.tar.gz\">${TARGET}.tar.gz</a></li>" >> ${PUBLISH_DIR}/index.html
echo "<li><a href=\"${TARGET}.zip\">${TARGET}.zip</a></li>" >> ${PUBLISH_DIR}/index.html

cat >> ${PUBLISH_DIR}/index.html <<EOF
</ul>

</div> <!-- section-body -->
</div> <!-- section -->

</td>
</tr>
</table>
</body>
</html>
EOF

# more cleanup
rm -rf ${EXPORTDIR}
