#!/bin/sh

# NOTE: Run this script from the root of the ViewVC checkout.
#
# $ ./tools/check-code-formatting

# The linting tools will generally find all the .py files, but we want
# to also add into the set of checked paths other Python files
# (scripts that reference Python in the shebang line, WSGI stubs,
# etc.)

echo "Checking code formatting..."
PYFILES=`grep -rl '^#\(!.*/\|.*-\)python' --exclude=*.py .`
black --line-length=100 --quiet --check . ${PYFILES} && flake8 . ${PYFILES}
if [ $? -eq 0 ]; then
    echo ""
    echo "Linting succeeded!"
else
    echo ""
    echo "Linting failed."
    echo "Try running 'black --line-length=100' on your problematic files."
fi
