name: CI
on:
  push:
    branches-ignore:
      - refs/heads/1.0.x
      - refs/heads/1.1.x
      - refs/heads/1.2.x
  pull_request:
    branches-ignore:
      - refs/heads/1.0.x
      - refs/heads/1.1.x
      - refs/heads/1.2.x
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install linting requirements
        run: pip install -r dev-requirements.txt
      - name: Check code formatting
        run: ./tools/check-code-formatting
